# -*- coding: utf-8 -*-
"""Streamlit_app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_06313SOBbkPdOvKlQRUJhNr98iU5KuM
"""

from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
import joblib

X,y = load_iris(return_X_y=True)
model = RandomForestClassifier()
model.fit(X,y)
joblib.dump(model,'model.pkl')

import streamlit as st
import numpy as np
import joblib

model = joblib.load("model.pkl")

st.title("꽃 분류(Iris Classifier)")
st.write("입력값을 기반으로 꽃의 종류를 예측합니다.")

sepal_length = st.slider("Sepal Length", 0.0, 10.0, 5.0)
sepal_width = st.slider("Sepal Width", 0.0, 10.0, 5.0)
petal_length = st.slider("Petal Length", 0.0, 10.0, 5.0)
petal_width = st.slider("Petal Width", 0.0, 10.0, 5.0)

input_data = np.array([[sepal_length, sepal_width, petal_length, petal_width]])
prediction = model.predict(input_data)

predicted_class = prediction[0]

class_names = ["Setosa", "Versicolor", "Virginica"]

st.subheader("예측 결과")
st.write(f"-> {class_names[predicted_class]}")

